# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'designed_interface.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDoubleSpinBox, QGroupBox, QLabel,
    QLineEdit, QMainWindow, QPushButton, QRadioButton,
    QSizePolicy, QSlider, QSpinBox, QStatusBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1099, 628)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.plot_area = QWidget(self.centralwidget)
        self.plot_area.setObjectName(u"plot_area")
        self.plot_area.setGeometry(QRect(0, 0, 851, 601))
        self.noise_slider = QSlider(self.centralwidget)
        self.noise_slider.setObjectName(u"noise_slider")
        self.noise_slider.setGeometry(QRect(860, 40, 160, 22))
        self.noise_slider.setMaximum(100)
        self.noise_slider.setSingleStep(0)
        self.noise_slider.setOrientation(Qt.Horizontal)
        self.noise_label = QLabel(self.centralwidget)
        self.noise_label.setObjectName(u"noise_label")
        self.noise_label.setGeometry(QRect(910, 20, 91, 16))
        self.noise_line = QLineEdit(self.centralwidget)
        self.noise_line.setObjectName(u"noise_line")
        self.noise_line.setGeometry(QRect(1040, 40, 31, 22))
        self.noise_line.setMouseTracking(True)
        self.filter_box = QGroupBox(self.centralwidget)
        self.filter_box.setObjectName(u"filter_box")
        self.filter_box.setGeometry(QRect(890, 80, 171, 141))
        self.average_radio = QRadioButton(self.filter_box)
        self.average_radio.setObjectName(u"average_radio")
        self.average_radio.setGeometry(QRect(10, 30, 161, 20))
        self.average_radio.setChecked(True)
        self.median_radio = QRadioButton(self.filter_box)
        self.median_radio.setObjectName(u"median_radio")
        self.median_radio.setEnabled(True)
        self.median_radio.setGeometry(QRect(10, 60, 95, 20))
        self.median_radio.setChecked(False)
        self.gausse_radio = QRadioButton(self.filter_box)
        self.gausse_radio.setObjectName(u"gausse_radio")
        self.gausse_radio.setGeometry(QRect(10, 90, 95, 20))
        self.exp_radio = QRadioButton(self.filter_box)
        self.exp_radio.setObjectName(u"exp_radio")
        self.exp_radio.setGeometry(QRect(10, 120, 151, 20))
        self.a1_spin = QDoubleSpinBox(self.centralwidget)
        self.a1_spin.setObjectName(u"a1_spin")
        self.a1_spin.setGeometry(QRect(890, 300, 62, 22))
        self.a1_spin.setSingleStep(0.010000000000000)
        self.a1_spin.setValue(1.000000000000000)
        self.a1_label = QLabel(self.centralwidget)
        self.a1_label.setObjectName(u"a1_label")
        self.a1_label.setGeometry(QRect(860, 300, 21, 21))
        self.a2_label = QLabel(self.centralwidget)
        self.a2_label.setObjectName(u"a2_label")
        self.a2_label.setGeometry(QRect(860, 340, 21, 21))
        self.a3_label = QLabel(self.centralwidget)
        self.a3_label.setObjectName(u"a3_label")
        self.a3_label.setGeometry(QRect(860, 380, 21, 21))
        self.b1_label = QLabel(self.centralwidget)
        self.b1_label.setObjectName(u"b1_label")
        self.b1_label.setGeometry(QRect(990, 300, 21, 21))
        self.b2_label = QLabel(self.centralwidget)
        self.b2_label.setObjectName(u"b2_label")
        self.b2_label.setGeometry(QRect(990, 340, 21, 21))
        self.b3_label = QLabel(self.centralwidget)
        self.b3_label.setObjectName(u"b3_label")
        self.b3_label.setGeometry(QRect(990, 380, 21, 21))
        self.x0_label = QLabel(self.centralwidget)
        self.x0_label.setObjectName(u"x0_label")
        self.x0_label.setGeometry(QRect(860, 420, 21, 21))
        self.xk_label = QLabel(self.centralwidget)
        self.xk_label.setObjectName(u"xk_label")
        self.xk_label.setGeometry(QRect(990, 420, 21, 21))
        self.dx_label = QLabel(self.centralwidget)
        self.dx_label.setObjectName(u"dx_label")
        self.dx_label.setGeometry(QRect(860, 460, 21, 21))
        self.a2_spin = QDoubleSpinBox(self.centralwidget)
        self.a2_spin.setObjectName(u"a2_spin")
        self.a2_spin.setGeometry(QRect(890, 340, 62, 22))
        self.a2_spin.setSingleStep(0.010000000000000)
        self.a2_spin.setValue(2.000000000000000)
        self.a3_spin = QDoubleSpinBox(self.centralwidget)
        self.a3_spin.setObjectName(u"a3_spin")
        self.a3_spin.setGeometry(QRect(890, 380, 62, 22))
        self.a3_spin.setSingleStep(0.010000000000000)
        self.a3_spin.setValue(0.500000000000000)
        self.x0_spin = QSpinBox(self.centralwidget)
        self.x0_spin.setObjectName(u"x0_spin")
        self.x0_spin.setGeometry(QRect(890, 420, 62, 22))
        self.dx_spin = QDoubleSpinBox(self.centralwidget)
        self.dx_spin.setObjectName(u"dx_spin")
        self.dx_spin.setGeometry(QRect(890, 460, 62, 22))
        self.dx_spin.setSingleStep(0.010000000000000)
        self.dx_spin.setValue(0.100000000000000)
        self.b1_spin = QDoubleSpinBox(self.centralwidget)
        self.b1_spin.setObjectName(u"b1_spin")
        self.b1_spin.setGeometry(QRect(1020, 300, 62, 22))
        self.b1_spin.setSingleStep(0.010000000000000)
        self.b1_spin.setValue(2.000000000000000)
        self.b2_spin = QDoubleSpinBox(self.centralwidget)
        self.b2_spin.setObjectName(u"b2_spin")
        self.b2_spin.setGeometry(QRect(1020, 340, 62, 22))
        self.b2_spin.setSingleStep(0.010000000000000)
        self.b2_spin.setValue(4.000000000000000)
        self.b3_spin = QDoubleSpinBox(self.centralwidget)
        self.b3_spin.setObjectName(u"b3_spin")
        self.b3_spin.setGeometry(QRect(1020, 380, 62, 22))
        self.b3_spin.setSingleStep(0.010000000000000)
        self.b3_spin.setValue(6.000000000000000)
        self.xk_spin = QSpinBox(self.centralwidget)
        self.xk_spin.setObjectName(u"xk_spin")
        self.xk_spin.setGeometry(QRect(1020, 420, 62, 22))
        self.xk_spin.setValue(10)
        self.func_params_label = QLabel(self.centralwidget)
        self.func_params_label.setObjectName(u"func_params_label")
        self.func_params_label.setGeometry(QRect(860, 260, 151, 31))
        self.scale_box = QGroupBox(self.centralwidget)
        self.scale_box.setObjectName(u"scale_box")
        self.scale_box.setGeometry(QRect(870, 510, 211, 80))
        self.scale_dec_button = QPushButton(self.scale_box)
        self.scale_dec_button.setObjectName(u"scale_dec_button")
        self.scale_dec_button.setGeometry(QRect(20, 30, 81, 24))
        self.scale_inc_button = QPushButton(self.scale_box)
        self.scale_inc_button.setObjectName(u"scale_inc_button")
        self.scale_inc_button.setGeometry(QRect(120, 30, 81, 24))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"SigNoise-generator by Aleksey Khaleev", None))
        self.noise_label.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0440\u043e\u0432\u0435\u043d\u044c \u0448\u0443\u043c\u0430", None))
        self.noise_line.setText(QCoreApplication.translate("MainWindow", u"0.00", None))
        self.filter_box.setTitle(QCoreApplication.translate("MainWindow", u"\u0424\u0438\u043b\u044c\u0442\u0440", None))
        self.average_radio.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043a\u043e\u043b\u044c\u0437\u044f\u0449\u0435\u0435 \u0441\u0440\u0435\u0434\u043d\u0435\u0435", None))
        self.median_radio.setText(QCoreApplication.translate("MainWindow", u"\u041c\u0435\u0434\u0438\u0430\u043d\u043d\u044b\u0439", None))
        self.gausse_radio.setText(QCoreApplication.translate("MainWindow", u"\u0413\u0430\u0443\u0441\u0441\u0430", None))
        self.exp_radio.setText(QCoreApplication.translate("MainWindow", u"\u042d\u043a\u0441\u043f\u043e\u043d\u0435\u043d\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0439", None))
        self.a1_label.setText(QCoreApplication.translate("MainWindow", u"a1", None))
        self.a2_label.setText(QCoreApplication.translate("MainWindow", u"a2", None))
        self.a3_label.setText(QCoreApplication.translate("MainWindow", u"a3", None))
        self.b1_label.setText(QCoreApplication.translate("MainWindow", u"b1", None))
        self.b2_label.setText(QCoreApplication.translate("MainWindow", u"b2", None))
        self.b3_label.setText(QCoreApplication.translate("MainWindow", u"b3", None))
        self.x0_label.setText(QCoreApplication.translate("MainWindow", u"X0", None))
        self.xk_label.setText(QCoreApplication.translate("MainWindow", u"Xk", None))
        self.dx_label.setText(QCoreApplication.translate("MainWindow", u"dX", None))
        self.func_params_label.setText(QCoreApplication.translate("MainWindow", u"\u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b \u0444\u0443\u043d\u043a\u0446\u0438\u0438:", None))
        self.scale_box.setTitle(QCoreApplication.translate("MainWindow", u"\u041c\u0430\u0441\u0448\u0442\u0430\u0431 \u043f\u043e \u043e\u0441\u0438 \"Y\"", None))
        self.scale_dec_button.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.scale_inc_button.setText(QCoreApplication.translate("MainWindow", u"+", None))
    # retranslateUi

